version: "3"

services:
  weather_api:
    build: ./weather_api
    ports:
      - "5000:5000"

  async_scheduler:
    build: ./async_scheduler
    depends_on:
      - db
      - weather_api
    environment:
      API_URL: weather_api
      API_PORT: 5000
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: test
      PG_PWD: test
      PG_DB: db_test
      UPDATE_TIMER: 5
      CITIES_FILENAME: 81_largest_city.txt

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER : test
      POSTGRES_PASSWORD: test
    ports:
      - 5444:5432
