PROJECT_NAME: WeatherAPP
PRJ_HOST: 127.0.0.1
PRJ_PORT: 5000

LOG_LEVEL: debug

POSTGRES_SERVER: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: postgres
POSTGRES_PASSWORD: nomnom
POSTGRES_DB: postgres
